package org.example.enums;

public enum Permission {
    VOTE_CLOSE, VOTE_DELETE, FLAG, POST_QUESTION, POST_ANSWER, POST_COMMENT,
    MOD_CLOSE, MOD_REOPEN, MOD_DELETE, MOD_RESTORE, ADMIN_BLOCK, ADMIN_UNBLOCK, ADMIN_AWARD_BADGE
}
